name: Flask-app-deploy

on:
    workflow_dispatch:

jobs:
    deploy:
        environment:
            DOCKER_USER= ${{vars.DOCKER_USER}}
            
        runs-on: self-hosted
        steps:

            - name: Checkout code
              uses: actions/checkout@v5

            - name: deploy from docker compose
              run: docker compose -f lint-files/docker-compose.yml up -d --build
          