name: Flask-app-deploy

on:
    workflow_run:
        workflows: ["Docker-BuildPush"]
        types: [completed]
        branches: 
            - main
jobs:
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        env:
            DOCKERHUB_USER: ${{vars.DOCKERHUB_USER}}
            IMAGE_TAG: ${{github.sha}}
            
        runs-on: self-hosted
        steps:

            - name: Checkout code
              uses: actions/checkout@v5

            - name: deploy from docker compose
              run: docker compose -f lint-files/docker-compose.yml up -d --build --force-recreate
          