name: Flask-app-deploy

on:
    workflow_dispatch:

jobs:
    deploy:
        env:
            DOCKERHUB_USER: ${{vars.DOCKERHUB_USER}}
            IMAGE_TAG: ${{github.sha}}
            
        runs-on: self-hosted
        steps:

            - name: Checkout code
              uses: actions/checkout@v5

            - name: deploy from docker compose
              run: docker compose -f lint-files/docker-compose.yml up -d --build --force-recreate
          