# This will deploy the safe/secure/ tested app to prod server
name: Deployment to server

on: 
    workflow_call:

jobs:
    deploy:
        runs-on: ubuntu-latest  #yeh  workflow run hamare server pe honga joh server ko ssh karenga
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: SSH to prod server and create app folder
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{secrets.EC2_SSH_HOST}}
                username:  ${{secrets.EC2_SSH_USER}}
                key:  ${{secrets.EC2_SSH_PRIVATE_KEY}}    # github ka runner is private ko use karke server ke andar jayenga
                script: |
                    echo "Installing required packages and folders"
                    sudo apt-get update && sudo apt-get install docker.io docker-compose-v2 -y
                    sudo usermod -aG docker $USER && newgrp docker
                    mkdir -p devops
            
            - name: Copy the docker compose file and build
              uses: appleboy/scp-action@v1
              with: 
                host: ${{secrets.EC2_SSH_HOST}}
                username:  ${{secrets.EC2_SSH_USER}}
                key:  ${{secrets.EC2_SSH_PRIVATE_KEY}}
                source: lint-files/docker-compose.yml
                target: ~/devops
          
            - name: SSH to prod server and run the app
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{secrets.EC2_SSH_HOST}}
                username:  ${{secrets.EC2_SSH_USER}}
                key:  ${{secrets.EC2_SSH_PRIVATE_KEY}}    # github ka runner is private ko use karke server ke andar jayenga
                script: |
                    echo "Running app"
                    export DOCKERHUB_USER= ${{vars.DOCKERHUB_USER}}
                    export IMAGE_TAG= ${{github.sha}}
                    echo ${{secrets.DOCKERHUB_TOKEN}} | docker login -u ${{vars.DOCKERHUB_USER}} --password-stdin 
                    cd ~/devops && docker compose up -d --build --force-recreate --pull always

